#ifndef ALI_CONVERTER_H
#define ALI_CONVERTER_H

#include "ast_visitor.hpp"
#include "config.hpp"
#include "node.hpp"
#include "alil.hpp"

#include <memory>
#include <string>
#include <unordered_map>



class ALILConverter : ASTVisitor {
    private:

        ALILCollection commands;
        void clean_command_list();

        std::string reserve_scoped_value_name();

        class NameScope {
            private:
                std::string old_name;
                ALILConverter *this_converter;
            public:
                NameScope(std::string, ALILConverter *);
                NameScope(std::string type_name, PNode id_node, ALILConverter *);
                ~NameScope();
        }; 
        
        // name of the current "scope" - makes the autogenerated names more clear
        // regardless of this, the names are guaranteed to be unique due to each value being given a new number       
        std::string current_scope_name;

        // valid for an object block - when we encounter the "this" keyword, what particle does that refer to?
        std::string what_object_is_this; 

        // valid for a region block - what is the running name of the region which the last action created?
        std::string what_region_are_we_in;

        // valid for a composite block - for our locally defined combinatoric names, what are the global names?
        std::unordered_map<std::string, std::string> what_global_name_for_this_comp_name;

        int highest_var_val;

        int iter_command;

        Config &config;

    protected:
        void visit_info(PNode node) override;
        void visit_definition(PNode node) override;
        void visit_composite(PNode node) override;
        void visit_object(PNode node) override;
        void visit_table_def(PNode node) override;
        void visit_region(PNode node) override;
        void visit_histo_list(PNode node) override;

        void visit_initializations(PNode node) override;

        void visit_comp_criteria(PNode node) override;

        void visit_object_criteria(PNode node) override;
        void visit_obj_union(PNode node) override;
        void visit_obj_sort(PNode node) override;
        void visit_object_select(PNode node) override;
        void visit_object_reject(PNode node) override;
    
        void visit_region_commands(PNode node) override;
        void visit_region_select(PNode node) override;
        void visit_region_reject(PNode node) override;
        void visit_region_use(PNode node) override;
        void visit_region_weight(PNode node) override;
        void visit_region_bin(PNode node) override;
        void visit_region_bins(PNode node) override;
        void visit_region_histo_use(PNode node) override;
        void visit_region_histogram(PNode node) override;

        void visit_histogram(PNode node) override;
        void visit_particle_sum(PNode node) override;
        void visit_variable_list(PNode node) override;

        void visit_expression(PNode node) override;
        void visit_operator_terminal(PNode node) override;
        void visit_index_operator(PNode node) override;
        void visit_if_statement(PNode node) override;

        void visit_within_statement(PNode node) override;
        void visit_outside_statement(PNode node) override;

        void visit_sort_expression(PNode node) override;
        void visit_min_expression(PNode node) override;
        void visit_max_expression(PNode node) override;

        void visit_negate(PNode node) override;
        void visit_l_not(PNode node) override;

        void visit_builtin_func_terminal(PNode node) override;
        void visit_user_function(PNode node) override;

        void visit_varying_terminal(PNode node) override;
        void visit_true_literal(PNode node) override;
        void visit_false_literal(PNode node) override;
        void visit_this_node(PNode node) override;

    public:
        ALILConverter(Config &conf);

        void visitation(PNode root);

        ALILCollection &get_commands();
        void print_commands();

        friend AnalysisCommandBuilder;
};


#define CONVERT_DISPATCH_DECLARE(ENUM, NAME) \
    virtual std::string convert_##NAME(const AnalysisCommand &) = 0;

class ALILToFrameworkCompiler {
    protected:
        std::unique_ptr<ALILConverter> alil;
        Config &config;

        ALIL_INSTRUCTION_LIST(CONVERT_DISPATCH_DECLARE)

        std::string command_convert(const AnalysisCommand &);
    public:
        ALILToFrameworkCompiler(ALILConverter *alil_in, Config &conf);
        virtual ~ALILToFrameworkCompiler() = default;
        virtual void print() = 0;
};

#undef CONVERT_DISPATCH_DECLARE
#endif